# Form implementation generated from reading ui file 'C:\Users\marat\PycharmProjects\scientific_calculator\ui\base_qt_ui\ui_main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 578)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.base_layout = QtWidgets.QVBoxLayout()
        self.base_layout.setObjectName("base_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_inputs_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clear_inputs_btn.setObjectName("clear_inputs_btn")
        self.horizontalLayout.addWidget(self.clear_inputs_btn)
        self.add_input_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_input_btn.setObjectName("add_input_btn")
        self.horizontalLayout.addWidget(self.add_input_btn)
        self.calculate_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_btn.setObjectName("calculate_btn")
        self.horizontalLayout.addWidget(self.calculate_btn)
        self.base_layout.addLayout(self.horizontalLayout)
        self.inputs_area = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.inputs_area.setWidgetResizable(True)
        self.inputs_area.setObjectName("inputs_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setEnabled(True)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 898, 490))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.coordwidget_layout = QtWidgets.QVBoxLayout()
        self.coordwidget_layout.setObjectName("coordwidget_layout")
        self.verticalLayout.addLayout(self.coordwidget_layout)
        self.inputs_area.setWidget(self.scrollAreaWidgetContents)
        self.base_layout.addWidget(self.inputs_area)
        self.results_label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.results_label.setFont(font)
        self.results_label.setObjectName("results_label")
        self.base_layout.addWidget(self.results_label)
        self.horizontalLayout_2.addLayout(self.base_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор для газов"))
        self.clear_inputs_btn.setText(_translate("MainWindow", "Очистить"))
        self.add_input_btn.setText(_translate("MainWindow", "Добавить"))
        self.calculate_btn.setText(_translate("MainWindow", "Рассчёт"))
        self.results_label.setText(_translate("MainWindow", "Результат рассчета:"))
